apiVersion: platform.juandc.dev/v1alpha1
kind: CoreApp
metadata:
  labels:
    app.kubernetes.io/name: platform-k8s-core-operator
    app.kubernetes.io/managed-by: kustomize
  name: coreapp-sample
spec:
  image: "nginxinc/nginx-unprivileged:alpine"
  port: 8080
  autoscaling:
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 75
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
